# Generated by Django 5.1.5 on 2025-02-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
